apiVersion: v1
kind: PersistentVolume
metadata:
  name: cnpg-db
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: cnpg-db
  hostPath:
    path: /mnt/zfs/db
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: cnpg-pvc
#  namespace: cnpg-db-cluster
#spec:
#  accessModes:
#    - ReadWriteMany
#  storageClassName: cnpg-storage
#  volumeName: cnpg-pv
#  resources:
#    requests:
#      storage: 10Gi
