apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-text-db
  namespace: cnpg-db
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3
  bootstrap:
    initdb:
      database: text_app_db
      owner: text_app
      secret:
        name: cnpg-text-app
  superuserSecret:
    name: cnpg-superuser
  monitoring:
    enabled: true
